//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertSetting
    {
        public System.Guid Id { get; set; }
        public System.Guid EngineModelID { get; set; }
        public System.Guid ChannelID { get; set; }
        public Nullable<int> Condition { get; set; }
        public string Value { get; set; }
        public Nullable<int> AlertLevel { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual Model Model { get; set; }
    }
}
