//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public System.Guid Id { get; set; }
        public Nullable<System.Guid> MonitoringId { get; set; }
        public Nullable<System.Guid> AlertSettingId { get; set; }
        public Nullable<int> AlertLevel { get; set; }
        public string Recipients { get; set; }
        public string Subject { get; set; }
        public string AlertMessage { get; set; }
    }
}
