//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Channel()
        {
            this.AlertSettings = new HashSet<AlertSetting>();
        }
    
        public System.Guid Id { get; set; }
        public string ChannelNo { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> ModelID { get; set; }
        public Nullable<bool> DashboardDisplay { get; set; }
        public Nullable<System.Guid> ChartTypeID { get; set; }
        public Nullable<decimal> MinRange { get; set; }
        public Nullable<decimal> MaxRange { get; set; }
        public Nullable<decimal> Scale { get; set; }
        public string DisplayUnit { get; set; }
        public Nullable<decimal> LowerLimit { get; set; }
        public Nullable<decimal> UpperLimit { get; set; }
        public Nullable<decimal> MonitoringTimer { get; set; }
        public Nullable<int> DataTypeNo { get; set; }
        public Nullable<int> Status { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string DocumentURL { get; set; }
    
        public virtual ChartType ChartType { get; set; }
        public virtual Model Model { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlertSetting> AlertSettings { get; set; }
    }
}
