//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string Id { get; set; }
        public string Secret { get; set; }
        public string Name { get; set; }
        public Nullable<int> ApplicationType { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<int> RefreshTokenLifeTime { get; set; }
        public string AllowedOrigin { get; set; }
    }
}
