//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardSetting
    {
        public System.Guid Id { get; set; }
        public System.Guid ModelNo { get; set; }
        public System.Guid ChannelNo { get; set; }
        public Nullable<bool> DisplayOnDashboard { get; set; }
        public int ChartType { get; set; }
        public Nullable<int> ChartGroupNo { get; set; }
    }
}
