//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine
    {
        public System.Guid Id { get; set; }
        public string IMO_No { get; set; }
        public string SerialNo { get; set; }
        public Nullable<System.Guid> EngineType { get; set; }
        public Nullable<System.Guid> EngineModel { get; set; }
        public Nullable<decimal> OutputPower { get; set; }
        public string GearBoxModel { get; set; }
        public string GearRatio { get; set; }
        public Nullable<System.Guid> AlternatorMaker { get; set; }
        public string AlternatorMakerModel { get; set; }
        public string AlternatorSrNo { get; set; }
        public Nullable<decimal> AlternatorOutput { get; set; }
        public string PowerSupplySystem { get; set; }
        public Nullable<decimal> InsulationTempRise { get; set; }
        public string IPRating { get; set; }
        public string Mounting { get; set; }
    }
}
