//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engine
    {
        public System.Guid Id { get; set; }
        public System.Guid VesselID { get; set; }
        public Nullable<System.Guid> EngineTypeID { get; set; }
        public Nullable<System.Guid> EngineModelID { get; set; }
        public string SerialNo { get; set; }
        public Nullable<decimal> OutputPower { get; set; }
        public Nullable<decimal> RPM { get; set; }
        public string GearBoxSerialNo { get; set; }
        public Nullable<System.Guid> GearBoxModelID { get; set; }
        public string GearRatio { get; set; }
        public Nullable<System.Guid> AlternatorMakerID { get; set; }
        public string AlternatorMakerModel { get; set; }
        public string AlternatorSrNo { get; set; }
        public Nullable<decimal> AlternatorOutput { get; set; }
        public string PowerSupplySystem { get; set; }
        public Nullable<decimal> InsulationTempRise { get; set; }
        public string IPRating { get; set; }
        public string Mounting { get; set; }
        public Nullable<int> AlertEmail { get; set; }
        public Nullable<int> Side { get; set; }
        public Nullable<int> Status { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual AlternatorMaker AlternatorMaker { get; set; }
        public virtual EngineType EngineType { get; set; }
        public virtual Model Model { get; set; }
        public virtual Vessel Vessel { get; set; }
        public virtual GearboxModel GearboxModel { get; set; }
    }
}
