//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monitoring
    {
        public System.Guid Id { get; set; }
        public string IMO_No { get; set; }
        public string SerialNo { get; set; }
        public int ChannelNo { get; set; }
        public string ChannelDescription { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Unit { get; set; }
        public string Value { get; set; }
    }
}
