//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionSet
    {
        public System.Guid Id { get; set; }
        public System.Guid GroupId { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
        public int SortOrder { get; set; }
    }
}
