//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourcePermission
    {
        public System.Guid RoleId { get; set; }
        public int ResourceId { get; set; }
        public Nullable<byte> ReadPermission { get; set; }
        public Nullable<byte> WritePermission { get; set; }
        public Nullable<byte> DeletePermission { get; set; }
        public Nullable<byte> ExecutePermission { get; set; }
    }
}
