//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vessel()
        {
            this.Engines = new HashSet<Engine>();
        }
    
        public System.Guid Id { get; set; }
        public string IMO_No { get; set; }
        public string VesselName { get; set; }
        public System.Guid OwnerID { get; set; }
        public System.Guid OperatorID { get; set; }
        public Nullable<System.Guid> ShipTypeID { get; set; }
        public string ShipyardName { get; set; }
        public Nullable<System.Guid> ShipyardCountry { get; set; }
        public Nullable<System.DateTime> BuildYear { get; set; }
        public Nullable<System.DateTime> DeliveryToOwner { get; set; }
        public Nullable<System.Guid> ShipClassID { get; set; }
        public Nullable<decimal> DWT { get; set; }
        public Nullable<decimal> TotalPropulsionPower { get; set; }
        public Nullable<decimal> TotalGeneratorPower { get; set; }
        public Nullable<int> Status { get; set; }
        public System.Guid CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.Guid ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        public virtual Account OperatorAccount { get; set; }
        public virtual Account OwnerAccount { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Engine> Engines { get; set; }
        public virtual ShipClass ShipClass { get; set; }
        public virtual ShipType ShipType { get; set; }
    }
}
