//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REMAXAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vessel
    {
        public System.Guid Id { get; set; }
        public string IMO_No { get; set; }
        public string VesselName { get; set; }
        public System.Guid OwnerID { get; set; }
        public System.Guid OperatorID { get; set; }
        public Nullable<System.Guid> ShipTypeID { get; set; }
        public string ShipyardName { get; set; }
        public Nullable<System.DateTime> BuildYear { get; set; }
        public Nullable<System.DateTime> DeliveryToOwner { get; set; }
        public Nullable<System.Guid> ShipClassID { get; set; }
        public Nullable<decimal> DWT { get; set; }
        public Nullable<decimal> TotalPropulsionPower { get; set; }
        public Nullable<decimal> TotalGeneratorPower { get; set; }
    }
}
